### ISSUE TITLE
Please use a recent version as an example in README

### ISSUE THREAD

**Issue by tenor-dev** [web-eid/web-eid-authtoken-validation-java#30]
Current version seems to be 2.0.1, but README uses 1.0.1.
Either specify a recent version or change it to some placeholder in README to avoid confusion.

**Comment by tenor-dev** [comment]
Also, the README still talks about Cache, but 2.0.1 no longer uses it (very good)

**Comment by mrts** [comment]
> Current version seems to be 2.0.1, but README uses 1.0.1.

The current version in the README Maven code snippet has been 2.0.0 since February, please see https://github.com/web-eid/web-eid-authtoken-validation-java/commit/97ad6775735aedcb436374e07356a047ee42d4b0.

Are you sure you are viewing the latest README?

But you are right that we should automate keeping the version in README in sync with the actual version in pom.xml.

> Also, the README still talks about Cache, but 2.0.1 no longer uses it (very good)

Maybe you are not viewing the latest README? The latest README talks about cache only in relevant sections "Stateful and stateless authentication" and "Upgrading from version 1 to version 2". Do you propose changing these sections?
