### ISSUE TITLE
Library crashes if there are expired Trusted CA certs configured

### ISSUE THREAD

**Issue by angryziber** [web-eid/web-eid-authtoken-validation-java#56]
It could be a warning, but not a crash just because one day (today) we have an expired cert not removed from production.

```
"error": "java.security.cert.CertificateExpiredException: NotAfter: Mon Mar 18 00:00:00 EET 2024",
    "stack": [
      ".CertificateValidity.valid(Unknown Source)",
      "java.base/sun.security.x509.X509CertImpl.checkValidity(Unknown Source)",
      ".certificateIsValidOnDate(CertificateValidator.java:52)",
      "eu.webeid.security.certificate.CertificateValidator.trustedCACertificatesAreValidOnDate(CertificateValidator.java:62)",
      ".SubjectCertificateExpiryValidator.validateCertificateExpiry(SubjectCertificateExpiryValidator.java:56)",
      ".certvalidators.SubjectCertificateValidatorBatch.executeFor(SubjectCertificateValidatorBatch.java:44)",
      ".validateToken(AuthTokenValidatorImpl.java:161)",
      "eu.webeid.security.validator.AuthTokenValidatorImpl.validate(AuthTokenValidatorImpl.java:122)",
      "(WebEidClient.kt:29)",
...
```

The problem appeared today with expired KLASS3 2010 certs.

**Comment by mrts** [comment]
Thank you for bringing this up! Yes, we are aware of this issue and we will provide a fix soon. To mitigate this error, please remove the expired KLASS3 2010 certificate from trusted certificate authorities. Our apologies for the inconvenience!

**Comment by mrts** [comment]
We have now modified the certificate validation process to only check the expiration of CA certificates that are directly part of the user's certificate chain. This ensures that the presence of unrelated expired certificates in the trusted certificate authorities will no longer cause the service to crash. The fix is [here](https://github.com/web-eid/web-eid-authtoken-validation-java/pull/59/commits/d61e8e7007421dae9c69a9de86cd403a6c8d0f23), comments very welcome!
